# Generated by Django 5.2 on 2026-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bgtest',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
