# Generated by Django 5.2 on 2026-01-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0002_bgdraft_remove_bgtest_status_bgtest_updated_at_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgtest',
            name='status',
        ),
    ]
