# Generated by Django 5.2 on 2026-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0003_delete_bgdraft_bgtest_order_number_unique_and_more_blue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BGDraft',
        ),
    ]
