# Generated by Django 5.2 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0002_bgdraft_remove_bgtest_status_bgtest_updated_at_green'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bgtest',
            constraint=models.UniqueConstraint(fields=('number',), name='order_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='bgtest',
            constraint=models.UniqueConstraint(fields=('number', 'created_at'), name='order_number_created_unique'),
        ),
    ]
