# Generated by Django 5.2 on 2026-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0004_remove_bgtest_order_number_unique_and_more_blue'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bgtest',
            name='order_number_unique',
        ),
        migrations.RemoveConstraint(
            model_name='bgtest',
            name='order_number_created_unique',
        ),
    ]
