# Generated by Django 5.2 on 2026-01-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluegreen', '0005_order_delete_bgtest_blue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BGTest',
        ),
    ]
